/**
 * Dev-time font build.
 *
 * Instance the vendored variable Roboto / Roboto Mono (SIL OFL 1.1, under
 * scripts/fonts-src/) to the weights the cards use, subset them to a fixed
 * ASCII+symbols charset, and write Base64 woff2 constants to
 * src/fonts.generated.ts. Runs locally / in CI only — subset-font never enters
 * the scheduled runtime, which reads only the committed constants.
 */

import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import subsetFont from "subset-font";

const srcDir = join(import.meta.dirname, "fonts-src");
const outFile = join(import.meta.dirname, "..", "src", "fonts.generated.ts");

// Fixed, deterministic glyph set: printable ASCII plus the Latin punctuation the
// cards emit. U+2192 (→) is deliberately excluded — it sits outside Google's
// "latin" subset, so directional arrows are drawn as SVG shapes, not glyphs.
const ASCII = Array.from({ length: 0x7e - 0x20 + 1 }, (_, i) =>
  String.fromCodePoint(0x20 + i),
).join("");
const SYMBOLS = " ·×–—‘’“”•…−€™";
const CHARSET = ASCII + SYMBOLS;

// Retain the OFL name-table records: copyright (0), trademark (7), license
// description (13), license URL (14).
const PRESERVE_NAME_IDS = [0, 7, 13, 14];

interface Face {
  readonly constName: string;
  readonly src: string;
  readonly wght: number;
}

const FACES: readonly Face[] = [
  { constName: "ROBOTO_200", src: "Roboto-latin-var.woff2", wght: 200 },
  { constName: "ROBOTO_400", src: "Roboto-latin-var.woff2", wght: 400 },
  { constName: "ROBOTO_600", src: "Roboto-latin-var.woff2", wght: 600 },
  { constName: "ROBOTO_MONO_400", src: "RobotoMono-latin-var.woff2", wght: 400 },
];

const sources = new Map<string, Buffer>();
async function source(name: string): Promise<Buffer> {
  const cached = sources.get(name);
  if (cached) return cached;
  const buf = await readFile(join(srcDir, name));
  sources.set(name, buf);
  return buf;
}

const header = [
  "/**",
  " * GENERATED by scripts/build-fonts.ts — do not edit by hand.",
  " *",
  " * Base64 woff2 for Roboto / Roboto Mono (SIL OFL 1.1; sources and license in",
  " * scripts/fonts-src/), instanced to single weights and subset to a fixed",
  " * ASCII+symbols charset. Consumed by src/fonts.ts.",
  " */",
  "",
];

const lines: string[] = [...header];
let total = 0;
for (const face of FACES) {
  const buf = await source(face.src);
  const out = await subsetFont(buf, CHARSET, {
    targetFormat: "woff2",
    variationAxes: { wght: face.wght },
    preserveNameIds: PRESERVE_NAME_IDS,
  });
  const b64 = out.toString("base64");
  total += out.length;
  lines.push(`export const ${face.constName} = "${b64}";`);
  console.log(`${face.constName}: ${out.length} B woff2 -> ${b64.length} B base64`);
}

await writeFile(outFile, `${lines.join("\n")}\n`, "utf8");
console.log(`wrote ${outFile} (${FACES.length} faces, ${total} woff2 bytes)`);
