name: LAPRAS Card

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  update-card:
    name: LAPRAS Card
    runs-on: ubuntu-latest
    steps:
      - uses: kawamataryo/lapras-card-readme@main
        with:
          SHARE_ID: "seijikohara"
          ICON_FIRST: "#888888"
          ICON_SECOND: "#cccccc"
          BACKGROUND_FIRST: "#767676"
          BACKGROUND_SECOND: "#e1e1e1"
          LANG: "en"
